# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00c2bdbd0ac017479723547b7b52548b"
name = "GESFaturação"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
scopes = "read_customers,read_orders,read_fulfillments,write_orders,write_fulfillments"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
