# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c15a6ca82509b5d77ffdec91ea2cd916"
name = "gesfaturacao"
application_url = "https://translator-cave-apt-valve.trycloudflare.com"
embedded = true
handle = "gesfaturacao-joaocunha-2025"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,write_fulfillments,write_orders"

[auth]
redirect_urls = [
  "https://translator-cave-apt-valve.trycloudflare.com/auth/callback",
  "https://translator-cave-apt-valve.trycloudflare.com/auth/shopify/callback",
  "https://translator-cave-apt-valve.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
