# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00c2bdbd0ac017479723547b7b52548b"
name = "GESFaturação"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
