# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c15a6ca82509b5d77ffdec91ea2cd916"
name = "gesfaturacao"
application_url = "http://localhost:64503"
embedded = true
handle = "gesfaturacao-3"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [
  "http://localhost:64503/auth/callback",
  "http://localhost:64503/auth/shopify/callback",
  "http://localhost:64503/api/auth/callback"
]

[pos]
embedded = false